export const ScreenType = {
  ALL_SCREEN: 0,
  SOICAL_WALL: 1,
  LEADER_BOARD: 2,
  ANALYTICS: 3,
  SOICAL_WALL_WITH_LEADER_BOARD: 4,
  SOICAL_WALL_WITH_ANALYTICS: 5,
};
export const ANIMATION_DURATION = 5000;
export const ANIMATION_DELAY_ON_EACH = 7000;
export const initialScreen = {
  title: "Dashboards",
  description: null,
  key: "1",
  duration: null,
  brands: null,
  sections: null,
  onlyWidgets: null,
  isDashboard: false,
  isDeepDive: false,
  deep_dive: {
    infoBar: null,
    mentions: null,
    wordcloud: [],
    category: [],
    top_users: [],
    influencers: [],
    source_of_post: [],
  },
  deepdive: { deepdiveResponse: [], tabName: null },
  pills: "All Dashboards",
  sortOrder: "asc",
  sortBy: "name",
  dashboard_template_filters: {
    filter_vals: [],
    search_text: "",
    pill: "All Dashboards",
    offset: 0,
    no_of_rows: 12,
    sort_expression: null,
    sort_order: null,
    type: "dashboard",
  },
  selected_duration_type: "Today",
  tagcloud_filter_pill: null,
  settings: {
    is_competitor: false,
    is_share_of_voice: false,
    color_style: "1",
    number_of_words: 50,
    font_family: "",
    post_presence_time: 5,
    post_presence_unit: "S",
    radius_attribute: null,
    number_of_nodes: 5,
  },
  category_screen_filters: [],
  stream_screen_brand: null,
  current_screen_brand: null,
  stream_screen_filters: [],
  stream_screen_default_widget: null,
  quick_filter: null,
  profiles: null,
  selected_quick_profile: null,
  campaign_date: null,
  markInfluencersList: [],
  markInfluencersFlag: false,
  deletePostFlag: false,
};
export const globalChartColor = [
  "#3076F7",
  "#9D48FF",
  "#60E340",
  "#FFB940",
  "#3FE7AC",
  "#FF6E31",
  "#8397F1",
  "#2968B9",
  "#00A669",
  "#FF7D6C",
  "#1C9F00",
  "#A77B00",
  "#FF4343",
  "#FF2EF2",
  "#B600AA",
  "#D19C00",
  "#39A7E4",
  "#6600DA",
  "#FFC1B9",
  "#FF9C73",
  "#FFD58B",
  "#96FF7C",
  "#6A8CFD",
  "#FF83F7",
  "#CD97FF",
  "#FFBE00",
  "#E84500",
  "#19CDCE",
  "#EF2E2E",
];
